# Generated by Django 4.0.4 on 2022-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('email', models.IntegerField()),
                ('contrasena', models.IntegerField()),
            ],
        ),
    ]
